{{- if .Values.deployConsoleInstance }}
{{- if and (not .Values.consoleInstance.hostname) (not .Values.clusterDomain) }}
  {{- fail "either consoleInstance.hostname or clusterDomain must be set when deployConsoleInstance is true" }}
{{- end }}
apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "streamshub-console-operator.labels" . | nindent 4 }}
spec:
  hostname: {{ include "streamshub-console-operator.consoleHostname" . | quote }}

  {{- if or .Values.exampleKafka.enabled .Values.consoleInstance.kafkaClusters }}
  kafkaClusters:
    {{- if .Values.exampleKafka.enabled }}
    - name: {{ include "streamshub-console-operator.kafkaName" . }}
      namespace: {{ .Values.exampleKafka.namespace | default .Release.Namespace }}
      listener: tls
      credentials:
        kafkaUser:
          name: {{ .Release.Name }}-kafka-user
    {{- end }}
    {{- if .Values.consoleInstance.kafkaClusters }}
    {{- toYaml .Values.consoleInstance.kafkaClusters | nindent 4 }}
    {{- end }}
  {{- end }}

  {{- if .Values.consoleInstance.kafkaConnectClusters }}
  kafkaConnectClusters:
    {{- toYaml .Values.consoleInstance.kafkaConnectClusters | nindent 4 }}
  {{- end }}

  {{- if .Values.consoleInstance.metricsSources }}
  metricsSources:
    {{- toYaml .Values.consoleInstance.metricsSources | nindent 4 }}
  {{- end }}

  {{- if .Values.consoleInstance.schemaRegistries }}
  schemaRegistries:
    {{- toYaml .Values.consoleInstance.schemaRegistries | nindent 4 }}
  {{- end }}

  {{- if .Values.consoleInstance.security }}
  security:
    {{- toYaml .Values.consoleInstance.security | nindent 4 }}
  {{- end }}

  {{- if .Values.consoleInstance.containers }}
  containers:
    {{- toYaml .Values.consoleInstance.containers | nindent 4 }}
  {{- end }}

{{- end }}