apiVersion: v2
name: streamshub-console-operator
description: User interface to monitor Apache Kafka® clusters
type: application
version: 0.11.0
appVersion: "0.11.0"
keywords:
  - kafka
  - messaging
  - streaming
  - console
  - operator
home: https://github.com/streamshub/console
sources:
  - https://github.com/streamshub/console
maintainers:
  - name: jankalinic
    email: jkalinic@redhat.com
