{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: streamshub-console-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "streamshub-console-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "streamshub-console-operator.selectorLabels" . | nindent 6 }}
  endpoints:
    - scheme: http
      targetPort: 8080
      path: /q/metrics
      interval: 10s
      honorLabels: true
{{- end }}
