apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "streamshub-console-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "streamshub-console-operator.labels" . | nindent 4 }}
