annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |-
    - name: Documentation
      url: https://github.com/streamshub/console/blob/main/README.md
    - name: Source
      url: https://github.com/streamshub/console
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Basic Install
apiVersion: v2
appVersion: 0.11.0
dependencies:
- condition: strimzi.enabled
  name: strimzi-kafka-operator
  repository: https://strimzi.io/charts/
  version: '>=0.50.0'
description: User interface to monitor Apache Kafka® clusters managed by Strimzi
home: https://github.com/streamshub/console
icon: https://raw.githubusercontent.com/jankalinic/console-helm-charts/refs/heads/main/resources/community-logo-white.png
keywords:
- kafka
- strimzi
- messaging
- streaming
- console
- operator
- monitoring
maintainers:
- email: work.kalinic@gmail.com
  name: jankalinic
name: streamshub-console-operator
sources:
- https://github.com/streamshub/console
type: application
version: 0.11.0
